draft pull request
netascode/terraform-sdwan-nac-sdwan pull request #34
Opened 2024-05-23 10:02 UTC by narasing01

draft pull request

2024-06-28 13:51 UTC, rrahimm commented on sdwan_policy_objects.tf
> +
please remove additional spaces

2024-06-28 13:52 UTC, rrahimm requested changes
please remove additional spaces

2024-07-01 12:11 UTC, rrahimm approved these changes
tested good

2024-07-08 09:32 UTC, rrahimm approved these changes

2024-07-08 09:33 UTC, rrahimm commented
Hello @danischm 

Kindly review and merge.

2024-07-08 10:30 UTC, narasing01 commented
duplicate of https://github.com/netascode/terraform-sdwan-nac-sdwan/pull/41

2024-07-08 10:30 UTC, closed without merging