TF modules for Zone_base firewall,feature policy and IPS policy . modifiy main.tf
netascode/terraform-sdwan-nac-sdwan pull request #41
Opened 2024-06-28 14:53 UTC by narasing01

@rrahimm  please review and share the review comments

2024-07-11 08:09 UTC, rrahimm requested changes
the key name is wrong >> fqdn_data_prefix_lists

it should be fqdn_lists

2024-07-11 08:09 UTC, rrahimm commented on sdwan_policy_objects.tf
> +  for_each = { for p in try(local.policy_objects.fqdn_data_prefix_lists, {}) : p.name => p }
the key name is wrong >> fqdn_data_prefix_lists

it should be fqdn_lists

2024-07-11 08:41 UTC, narasing01 commented
@rrahimm  review comments incorporate.

2024-07-11 10:34 UTC, narasing01 commented
@rrahimm  added the dependency in device templates for security policy

2024-07-11 14:22 UTC, rrahimm commented
Hello @danischm 

Can you please review and approve

2024-07-12 05:37 UTC, rrahimm commented
hello @tzarski0 

Can you review and approve this.

2024-07-12 10:27 UTC, tzarski0 approved these changes
approve

2024-07-12 10:27 UTC, merged